### ISSUE TITLE
i can't run on xcode last version

### ISSUE THREAD

**Issue by huayai** [foundry/OpenCVSquares#1]
i can't run on xcode last version

help please...

**Comment by foundry** [comment]
See latest commits with update for XCode 8.2. 

The code is still using a 2013-era build of OpenCV. For 64-bit compatibilty you will want to switch to a recent build, see notes [here](https://github.com/foundry/OpenCVSwiftStitch)

**Comment by huayai** [comment]
Thanks for the advice.
But ask me I think I need to improve my education. The position of the floor plan to handle it.
